### ISSUE TITLE
Investigate stream and captured output

### ISSUE THREAD

**Issue by dkp** [vsoch/scif#59]
Great tool!  Thanks for creating and maintaining it.
I'm wondering if there is a way for scif to provide standard output as it runs my scripts?

Expected behavior: statements generated in a for loop are echoed to standard out as each item gets processed.

Observed behavior: the script runs all the way through, and only when it is finished, the statements are echoed to standard out.

Obviously, this is a minor issue, but it gives me peace of mind to see the outputs are really being generated and it isn't just hanging.

**Comment by vsoch** [comment]
It’s just how it’s designed - to capture the output we don’t stream but instead capture it and print at the end. If you’d like to take a look at the code I’d be happy to review a PR!

**Comment by dkp** [comment]
Thanks, I will think about it, but my Python is VERY rudimentary. I appreciate the quick reply.

**Comment by vsoch** [comment]
If I can make some time tomorrow I’ll think about this too! It’s possible to redirect output with bash so there might be a Python trick. I didn’t know when I was writing it but it’s worth a second look.

**Comment by dkp** [comment]
Gosh, thanks so much...

**Comment by vsoch** [comment]
hey @dkp I have a PR for you to test :point_right: https://github.com/vsoch/scif/pull/60 you can either test by installing locally (making sure to remove previous versions) or by using the release candidate container. For both, I put instructions in the description of the PR.

What it should do is to (instead of using process.communicate()) run the process and poll it for a return code, each line grabbing the output to save to return to the user, and also printing to the terminal if quiet is not True. Let me know if this is what you had in mind!

**Comment by vsoch** [comment]
Fixed with #60

**Comment by vsoch** [comment]
okay, one final note! The conda recipe was merged this morning, so I've also released 0.0.78 on pypi:

https://pypi.org/project/scif/0.0.78/

Also, the automated builds (as a quick reminder) are going to quay.io - the version with the fix you need is tag 0.0.78 https://quay.io/repository/scif/scif?tab=tags

**Comment by dkp** [comment]
Many many thanks!

-Dianne
________________________________
